version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - connections

  # dotnet:
  #   build: backend
  #   container_name: server
  #   environment:
  #     - MongoDB__ConnectionUri: "mongodb://root:example@mongodb:27017"
  #   networks:
  #     - connections




volumes:
  mongo-data:

networks:
  connections: