services:
  # mongodb:
  #   image: mongo:7.0
  #   container_name: mongo-container
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   volumes:
  #     - mongo-data:/data/db
  #   networks:
  #     - connections

  redis:
    image: redis
    container_name: redis
    networks:
    - connections
    ports:
    - "6379:6379"


  gamehub:
    build:
      context: ./backend
    container_name: server
    depends_on:
      - redis
    environment:
      - ConnectionStrings__Redis=redis:6379
    networks:
      - connections
    ports:
      - "8080:8080"

  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - gamehub
    networks:
      - connections

# volumes:
#   mongo-data:

networks:
  connections: