apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websocket_ingress
  labels:
    app.kubernetes.io/name: websocket_ingress
  annotations:
    nginx.ingress.kubernetes.io/websocket-services: "gamehub"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/gamehub/(.*)"
        backend:
          service:
            name: nginx
            port: 
              number: 80
