name: frontend
on:
  push:
    branches:
      - "main"
    paths:
     - 'frontend/**'
  workflow_dispatch:

jobs:
  push_to_registry:
    name: build & push frontend image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push frontend
        id: build-push-frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: stran9682/latest-amd64
